version: 2
jobs:
  test-3.7: &test-anchor
    docker:
      - image: circleci/python:3.7

    working_directory: ~/scrapy-xlsx

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.6:
    <<: *test-anchor
    docker:
      - image: circleci/python:3.6
workflows:
  version: 2
  workflow:
    jobs:
    - test-3.7
    - test-3.6