version: 2
jobs:
  test-py37: &test-anchor
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37
    working_directory: ~/scrapy-xlsx
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox
  test-py36:
    <<: *test-anchor
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36
workflows:
  version: 2
  workflow:
    jobs:
    - test-py37
    - test-py36
